### ISSUE TITLE
After Event Location

### ISSUE THREAD

**Issue by anthonysterling** [phpne/phpne.github.io#37]
Following @tempertemper's [Tweet](https://twitter.com/tempertemper/status/555033639239823361):

> @phpne Your footer says the Telegraph is just across the road. Does this need updating since the move to CampusNorth?

Should the ["After the Event"](https://github.com/phpne/phpne.github.io/blob/master/_layouts/default.html#L65) section be updated?

**Comment by mkpeacock** [comment]
Many thanks Messrs Sterling and Underhill!

**Comment by tempertemper** [comment]
Pleasure :)
