### ISSUE TITLE
phpne.org.uk is down

### ISSUE THREAD

**Issue by anthonysterling** [phpne/phpne.github.io#57]
👋 friends!

I couldn't find a way to contact the group, and this seemed to be the most accessible.

I'm not sure if you're aware, but website is unavailable at https://phpne.org.uk/ and the plain ol' http version hits a namecheap landing page.

> dig phpne.org.uk
<details>

```
; <<>> DiG 9.10.6 <<>> phpne.org.uk
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28429
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;phpne.org.uk.			IN	A

;; ANSWER SECTION:
phpne.org.uk.		587	IN	A	198.54.117.198
phpne.org.uk.		587	IN	A	198.54.117.199
phpne.org.uk.		587	IN	A	198.54.117.200
phpne.org.uk.		587	IN	A	198.54.117.197

;; Query time: 20 msec
;; SERVER: 10.0.0.1#53(10.0.0.1)
;; WHEN: Sat Oct 10 12:00:13 BST 2020
;; MSG SIZE  rcvd: 105
```
</details>

> curl -I https://phpne.org.uk
<details>

```
curl: (7) Failed to connect to phpne.org.uk port 443: Connection refused
```
</details>

/cc @nthndnn

**Comment by nthndnn** [comment]
Hey @anthonysterling, thanks for letting us know. @mkpeacock has renewed the domain and normal service should be resumed shortly!

Thanks again 🙂
